[display]
list_limit = 10
show_notes = true
show_headers = false
time_format = "%Y-%m-%d %H:%M:%S"
columns = ["name", "status", "last_touched"]

[sorting]
# name / time
by = "last_touched"

# ascending / descending
direction = "descending"

[projects]
# Status assigned to newly logged projects
default_status = "unknown"
ignore = [
    ".git",
    "dist",
    ".venv",
    "build",
    "target",
    "node_modules"
]

[scan]
detect_git = true

# Search recursively below the supplied path
recursive = true

# Do not scan inside an already detected Git project
stop_at_project = true

[output]
colour = true
compact = false
absolute_paths = true

[database]
file = "data.pkl"

[logging]
always_verbose = false